Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Iris dataset

In [2]:
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

Assigning column names

In [4]:
headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

Reading dataset

In [5]:
dataset = pd.read_csv(path, names=headernames)
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Data Preprocessing

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

We will divide the data into train and test split. The following code will split the dataset into 70% training data and 30% of testing data

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)


Train the model with the help of RandomForestClassifier class of sklearn as follows

In [8]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=50)
classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50)

Making prediction

In [9]:
y_pred = classifier.predict(X_test)

Results

In [10]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[11  0  0]
 [ 0 20  0]
 [ 0  3 11]]
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.87      1.00      0.93        20
 Iris-virginica       1.00      0.79      0.88        14

       accuracy                           0.93        45
      macro avg       0.96      0.93      0.94        45
   weighted avg       0.94      0.93      0.93        45

Accuracy: 0.9333333333333333
